services:
  - type: web
    name: telegramcryptobot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python runbot.py
    envVars:
      - key: PORT
        value: 10000
    plan: free
    region: frankfurt
